-- Seed metadata for sign category options in regulatory, cautionary, and informational categories
INSERT INTO sign_metadata (id, meta_key, meta_value, id_category, id_options, human_label, modifiable, unit) VALUES
-- Regulatory Sign options (id_category=1)
(1, 'width', '8', 1, 1, 'Width', false, 'inch'),
(2, 'height', '8', 1, 1, 'Height', false, 'inch'),
(3, 'title_font_size', '66', 1, 1, 'Title Font Size', false, 'pt'),
(4, 'subtitle_font_size', '26', 1, 1, 'Subtitle Font Size', false, 'pt'),
(5, 'regulation_font_size', '12', 1, 1, 'Regulation Font Size', false, 'pt'),
(6, 'width', '12', 1, 2, 'Width', false, 'inch'),
(7, 'height', '16', 1, 2, 'Height', false, 'inch'),
(8, 'title_font_size', '114', 1, 2, 'Title Font Size', false, 'pt'),
(9, 'subtitle_font_size', '60', 1, 2, 'Subtitle Font Size', false, 'pt'),
(10, 'regulation_font_size', '24', 1, 2, 'Regulation Font Size', false, 'pt'),
(11, 'width', '24', 1, 3, 'Width', false, 'inch'),
(12, 'height', '36', 1, 3, 'Height', false, 'inch'),
(13, 'title_font_size', '192', 1, 3, 'Title Font Size', false, 'pt'),
(14, 'subtitle_font_size', '90', 1, 3, 'Subtitle Font Size', false, 'pt'),
(15, 'regulation_font_size', '48', 1, 3, 'Regulation Font Size', false, 'pt'),
(16, 'width', '36', 1, 4, 'Width', false, 'inch'),
(17, 'height', '24', 1, 4, 'Height', false, 'inch'),
(18, 'title_font_size', '192', 1, 4, 'Title Font Size', false, 'pt'),
(19, 'subtitle_font_size', '92', 1, 4, 'Subtitle Font Size', false, 'pt'),
(20, 'regulation_font_size', '48', 1, 4, 'Regulation Font Size', false, 'pt'),
-- Cautionary Sign options (id_category=2)
(21, 'width', '8', 2, 5, 'Width', false, 'inch'),
(22, 'height', '8', 2, 5, 'Height', false, 'inch'),
(23, 'title_font_size', '66', 2, 5, 'Title Font Size', false, 'pt'),
(24, 'subtitle_font_size', '26', 2, 5, 'Subtitle Font Size', false, 'pt'),
(25, 'regulation_font_size', '12', 2, 5, 'Regulation Font Size', false, 'pt'),
(26, 'width', '12', 2, 6, 'Width', false, 'inch'),
(27, 'height', '16', 2, 6, 'Height', false, 'inch'),
(28, 'title_font_size', '114', 2, 6, 'Title Font Size', false, 'pt'),
(29, 'subtitle_font_size', '60', 2, 6, 'Subtitle Font Size', false, 'pt'),
(30, 'regulation_font_size', '24', 2, 6, 'Regulation Font Size', false, 'pt'),
(31, 'width', '24', 2, 7, 'Width', false, 'inch'),
(32, 'height', '36', 2, 7, 'Height', false, 'inch'),
(33, 'title_font_size', '192', 2, 7, 'Title Font Size', false, 'pt'),
(34, 'subtitle_font_size', '90', 2, 7, 'Subtitle Font Size', false, 'pt'),
(35, 'regulation_font_size', '48', 2, 7, 'Regulation Font Size', false, 'pt'),
(36, 'width', '36', 2, 8, 'Width', false, 'inch'),
(37, 'height', '24', 2, 8, 'Height', false, 'inch'),
(38, 'title_font_size', '192', 2, 8, 'Title Font Size', false, 'pt'),
(39, 'subtitle_font_size', '92', 2, 8, 'Subtitle Font Size', false, 'pt'),
(40, 'regulation_font_size', '48', 2, 8, 'Regulation Font Size', false, 'pt'),
-- Informational Sign options (id_category=3)
(41, 'width', '8', 3, 9, 'Width', false, 'inch'),
(42, 'height', '8', 3, 9, 'Height', false, 'inch'),
(43, 'title_font_size', '66', 3, 9, 'Title Font Size', false, 'pt'),
(44, 'subtitle_font_size', '26', 3, 9, 'Subtitle Font Size', false, 'pt'),
(45, 'regulation_font_size', '12', 3, 9, 'Regulation Font Size', false, 'pt'),
(46, 'width', '12', 3, 10, 'Width', false, 'inch'),
(47, 'height', '16', 3, 10, 'Height', false, 'inch'),
(48, 'title_font_size', '114', 3, 10, 'Title Font Size', false, 'pt'),
(49, 'subtitle_font_size', '60', 3, 10, 'Subtitle Font Size', false, 'pt'),
(50, 'regulation_font_size', '24', 3, 10, 'Regulation Font Size', false, 'pt'),
(51, 'width', '24', 3, 11, 'Width', false, 'inch'),
(52, 'height', '36', 3, 11, 'Height', false, 'inch'),
(53, 'title_font_size', '192', 3, 11, 'Title Font Size', false, 'pt'),
(54, 'subtitle_font_size', '90', 3, 11, 'Subtitle Font Size', false, 'pt'),
(55, 'regulation_font_size', '48', 3, 11, 'Regulation Font Size', false, 'pt'),
(56, 'width', '36', 3, 12, 'Width', false, 'inch'),
(57, 'height', '24', 3, 12, 'Height', false, 'inch'),
(58, 'title_font_size', '192', 3, 12, 'Title Font Size', false, 'pt'),
(59, 'subtitle_font_size', '92', 3, 12, 'Subtitle Font Size', false, 'pt'),
(60, 'regulation_font_size', '48', 3, 12, 'Regulation Font Size', false, 'pt');
